services:
  api:
    build: .
    image: ironcircle-api
    container_name: ironcircle-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/ironcircle

  mongo:
    image: mongo:7
    container_name: ironcircle-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0
    container_name: ironcircle-mongo-express
    ports:
      - "8080:8080"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
    depends_on:
      - mongo

volumes:
  mongo_data:
